spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://root:root@localhost:27017/bezkoder_db?authSource=admin

logging:
  level:
    org:
      springframework:
        data:
          mongodb: DEBUG
